# Generated by Django 4.1.3 on 2022-12-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWetzel', '0002_remove_fliawetzel_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fliawetzel',
            name='año_nacimiento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
